# Generated by Django 5.1.4 on 2025-05-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_otp_profile_remove_studentprofile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=6, unique=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classing', to='api.lecturerprofile')),
                ('students', models.ManyToManyField(blank=True, related_name='joined_classes', to='api.studentprofile')),
            ],
        ),
    ]
