# Generated by Django 5.1.4 on 2025-06-22 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=6, unique=True)),
                ('max_students', models.PositiveIntegerField()),
                ('group', models.PositiveIntegerField(default=1)),
                ('min_group_members', models.PositiveIntegerField(default=1)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.lecturerprofile')),
                ('students', models.ManyToManyField(blank=True, related_name='joined_classes', to='api.studentprofile')),
            ],
        ),
    ]
