# Generated by Django 5.1.4 on 2025-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Class',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
