# Generated by Django 5.1.4 on 2025-05-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0002_alter_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Class',
            old_name='id',
            new_name='class_id',
        ),
    ]
