# Generated by Django 5.1.4 on 2025-05-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0003_rename_id_class_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='Class',
            name='max_students',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
