# Generated by Django 5.1.4 on 2025-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0005_alter_class_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='Class',
            name='group',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='Class',
            name='max_group_members',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
