# Generated by Django 5.1.4 on 2025-05-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_lecturerprofile_class_count_and_more'),
        ('classing', '0006_class_group_class_max_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.lecturerprofile'),
        ),
    ]
