# Generated by Django 5.1.4 on 2025-05-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0007_alter_class_lecturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='max_group_members',
            new_name='min_group_members',
        ),
    ]
