# Generated by Django 5.1.4 on 2025-05-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0008_rename_max_group_members_class_min_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='group',
        ),
    ]
