# Generated by Django 5.1.4 on 2025-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0009_remove_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='group',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
