# Generated by Django 5.1.4 on 2025-06-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0010_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_temp_groups',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
