# Generated by Django 5.1.4 on 2025-06-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0011_class_max_temp_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='max_temp_groups',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
