# Generated by Django 5.1.4 on 2025-06-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classing', '0012_alter_class_max_temp_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='max_temp_groups',
        ),
    ]
