# Generated by Django 5.1.4 on 2025-06-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15, unique=True)),
                ('major', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(default='lecturer_profile_image/default.jpg', upload_to='lecturer_profile_image/')),
            ],
        ),
        migrations.CreateModel(
            name='OTP_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('expriarationDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('major', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(default='student_profile_image/default.jpg', upload_to='student_profile_image/')),
                ('bio', models.TextField(default='Bio loading… please wait.', max_length=200)),
                ('instagram_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
