# Generated by Django 5.1.4 on 2025-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lecturerprofile_id_alter_studentprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
