# Generated by Django 5.1.4 on 2025-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lecturerprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('expriarationDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(default='test', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
