# Generated by Django 5.1.4 on 2025-05-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lecturerprofile_class_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='class_count',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='joined_class_count',
        ),
    ]
