# Generated by Django 5.1.4 on 2025-06-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_lecturerprofile_class_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='major',
            field=models.CharField(default='Undeclared', max_length=50),
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='lecturer_profile_image/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(default='This user has not written a bio yet.', max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(default='Undeclared', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='student_profile_image/'),
        ),
    ]
