# Generated by Django 5.1.4 on 2025-06-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lecturerprofile_major_lecturerprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='major',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(max_length=50),
        ),
    ]
