# Generated by Django 5.1.4 on 2025-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_studentprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='instagram_link',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
