# Generated by Django 5.1.4 on 2025-05-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grouping.group'),
        ),
    ]
