# Generated by Django 5.1.4 on 2025-06-24 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('grouping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinGroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_received_requests', to='api.studentprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_sent_requests', to='api.studentprofile')),
                ('temp_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='grouping.temporarygroup')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
