# Generated by Django 5.1.4 on 2025-06-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarygroup',
            name='group_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
