# Generated by Django 5.1.4 on 2025-06-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0002_temporarygroup_group_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarygroup',
            name='group_number',
        ),
    ]
