# Generated by Django 5.1.4 on 2025-06-21 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_lecturerprofile_profile_image_and_more'),
        ('classing', '0011_class_max_temp_groups'),
        ('grouping', '0002_grouprequest_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_groups', to='classing.class')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_temp_groups', to='api.studentprofile')),
                ('members', models.ManyToManyField(related_name='temp_groups', to='api.studentprofile')),
            ],
        ),
    ]
