# Generated by Django 5.1.4 on 2025-06-21 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_lecturerprofile_profile_image_and_more'),
        ('grouping', '0003_temporarygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarygroup',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='temporarygroup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_temp_groups', to='api.studentprofile'),
        ),
        migrations.AlterField(
            model_name='temporarygroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='temp_groups', to='api.studentprofile'),
        ),
    ]
